// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/check-enrollment-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/check-enrollment-status.get').default>>>>
    }
    '/api/create-order': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/create-order.post').default>>>>
    }
    '/api/razorpay-webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/razorpay-webhook.post').default>>>>
    }
    '/api/se-register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/se-register.post').default>>>>
    }
    '/api/upload-image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload-image.post').default>>>>
    }
    '/api/verify-payment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/verify-payment.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}