import { readFileSync, existsSync, readdirSync } from 'fs'
import { resolve } from 'path'

// Dev-only preview of the college outreach email.
// Open: /api/outreach-preview                        (master template)
//       /api/outreach-preview?code=IITPKD26_SE       (that college's built copy)
//       /api/outreach-preview?code=IITPKD26_SE&variant=forward
//
// The per-college files under emails/colleges/ are generated by
// `npm run emails:build`, so previewing one shows what would actually be sent
// rather than the template it came from — the two drift whenever the master is
// edited without a rebuild.
//
// The stored files are body fragments as Gmail delivered them (no <html>
// wrapper), so they're wrapped in a minimal document here to render the way a
// mail client would. Read fresh on every request so edits show up on refresh.
export default defineEventHandler((event) => {
  if (process.env.NODE_ENV === 'production') {
    throw createError({ statusCode: 404, statusMessage: 'Not found' })
  }

  const q = getQuery(event)
  const code = typeof q.code === 'string' ? q.code.trim().toUpperCase() : ''
  const variant = q.variant === 'forward' ? '-forward' : ''

  // Codes reach the filesystem, so allow only the shape real ones take.
  if (code && !/^[A-Z0-9_]+$/.test(code)) {
    throw createError({ statusCode: 400, statusMessage: 'Invalid code' })
  }

  const rel = code ? `emails/colleges/${code}${variant}.html` : 'emails/college-outreach.html'
  const file = resolve(process.cwd(), rel)
  if (!existsSync(file)) {
    const built = existsSync(resolve(process.cwd(), 'emails/colleges'))
      ? readdirSync(resolve(process.cwd(), 'emails/colleges'))
          .filter((f) => f.endsWith('.html'))
          .join(', ')
      : ''
    throw createError({
      statusCode: 404,
      statusMessage: `${rel} not found${built ? `. Available: ${built}` : ''}`,
    })
  }

  const fragment = readFileSync(file, 'utf-8')

  setHeader(event, 'content-type', 'text/html; charset=utf-8')
  setHeader(event, 'cache-control', 'no-store')
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Outreach email preview — ${rel}</title>
    <style>
      body { margin: 0; background: #eef1f8; }
      .bar {
        font: 13px -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif;
        background: #0b1f4d; color: #fff; padding: 10px 16px;
      }
      .bar b { color: #ffd24a; }
    </style>
  </head>
  <body>
    <div class="bar">Preview — <b>${rel}</b> · refresh to see edits</div>
    ${fragment}
  </body>
</html>`
})
