// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/31/2026, 1:42:25 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/anuanura/Desktop/Success/GitaUnlocked/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/anuanura/Desktop/Success/GitaUnlocked/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/anuanura/Desktop/Success/GitaUnlocked/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/anuanura/Desktop/Success/GitaUnlocked/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/anuanura/Desktop/Success/GitaUnlocked/plugins/**/*.{js,ts,mjs}","/Users/anuanura/Desktop/Success/GitaUnlocked/composables/**/*.{js,ts,mjs}","/Users/anuanura/Desktop/Success/GitaUnlocked/utils/**/*.{js,ts,mjs}","/Users/anuanura/Desktop/Success/GitaUnlocked/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/anuanura/Desktop/Success/GitaUnlocked/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/anuanura/Desktop/Success/GitaUnlocked/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/anuanura/Desktop/Success/GitaUnlocked/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;